### ISSUE TITLE
Volcanoes erupting right next to each other

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#1]
![image](https://user-images.githubusercontent.com/106923/50034658-92b76c00-ffc3-11e8-9aa8-575bf34557fd.png)
![image](https://user-images.githubusercontent.com/106923/50034679-a19e1e80-ffc3-11e8-92be-606c9daf2df4.png)

### ...play other places, let the two volcanoes grow next to each other...

![image](https://user-images.githubusercontent.com/106923/50034711-cdb99f80-ffc3-11e8-9912-78933771c6c1.png)
![image](https://user-images.githubusercontent.com/106923/50034741-e2963300-ffc3-11e8-91da-1d7c78cc229c.png)

Looks like blue erupts first, expands and reduces the level 4 orange volcano to a 3. I think it would be more fair if they both erupted at the same time and then reduced each other from level 1 volcanoes to level 4 magma chambers.

**Comment by skotz** [comment]
I'll need to process the eruptions in two phases to do this. One to keep a list of deltas received from each neighbor as eruptions are processed, and the second to calculate the new value (and and team in some cases).

![image](https://user-images.githubusercontent.com/11474654/50035396-7f0e0480-ffc7-11e8-8db4-694ed4001912.png)

**Comment by skotz** [comment]
@simondorfman How would handle a situation where two volcanoes fill into a blank tile? I'm thinking they would just cancel out and leave the tile empty. Sound good?

![image](https://user-images.githubusercontent.com/11474654/50035800-b7aedd80-ffc9-11e8-87d9-7765742abb60.png)

And if an empty tile gets filled in from two blue eruptions and one orange, the net effect would be one blue.

**Comment by skotz** [comment]
Done:

![image](https://user-images.githubusercontent.com/11474654/50036269-57219f80-ffcd-11e8-8498-35d9daf0d9d7.png)

![image](https://user-images.githubusercontent.com/11474654/50036287-74566e00-ffcd-11e8-9450-8541cf920a35.png)

Also:

![image](https://user-images.githubusercontent.com/11474654/50036690-61916880-ffd0-11e8-9ce1-942989c7bdcc.png)

![image](https://user-images.githubusercontent.com/11474654/50036705-7ff76400-ffd0-11e8-8883-8362368f057b.png)

Makes sense to me.

**Comment by simondorfman** [comment]
@skotz Re: "How would handle a situation where two volcanoes fill into a blank tile? I'm thinking they would just cancel out and leave the tile empty. Sound good?"
Yeah, sounds good to me too.

Re: the 3 volcanoes erupting onto the same spot. that makes sense to me too.
