### ISSUE TITLE
bug: playing on level 3 volcano right before growth phase wierdness

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#10]
I think I may have found a bug. It can only happen right before a growth phase.

1. Player one's turn
2. Player two's turn **(on this turn, player two plays on a level 3 volcano, converting it to a level 4, causing eruption, it resolves in non-consistent ways, in my experience. it should finish resolving the eruption and then turn into a level 1 volcano before the next growth phase happens)**
3. Growth (every non-empty tile on the board is advanced one level on the growth track)
4. Player two's turn
5. Player one's turn **(on this turn player one can cause the same bug by playing on their level 3 volcano)**
6. Growth

screenshot of player one's blue level 3 volcano right before playing on it before growth:

![image](https://user-images.githubusercontent.com/106923/50380806-7a85c380-0639-11e9-96aa-a54a447913a8.png)

screenshot after playing on the level 3 volcano and growth happening:

![image](https://user-images.githubusercontent.com/106923/50380810-af921600-0639-11e9-828e-d1a38ca4fc63.png)

It seems to trigger the volcano twice because the triangles around it are level 2 chambers.

**Comment by skotz** [comment]
@simondorfman Could you include a transcript of a game that demonstrates the bug? That'll help me reproduce the issue faster.

**Comment by skotz** [comment]
I'm not seeing the issue. The eruption happens creating three new level one tiles and turning the volcano back into a level one. On the very next turn, every tile on the map grows, so all the new level one tiles turn to level two, and the volcano turns to level two.

```
7A 13B G 9C 9A G 9D 14B G 10C 10A G 7A 13A G 13C 7A G 9B 14D G 14A 14C G
```

**Comment by simondorfman** [comment]
Yeah, I'm pretty sure I just made a mistake in my thinking. Silly me. After my game simulations finish I'll try again. I first encountered it with some custom rules. If I can reproduce something, I'll include the game transcript. Otherwise I'll reply and just ask you to close this as a non-issue.

**Comment by simondorfman** [comment]
@skotz Yeah, I was just wrong. You can close this. Sorry to waste your time on this.
