### ISSUE TITLE
make eruption chains more visible

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#11]
As I'm stepping through games, and playing games, I often can't really follow all the eruptions and chain eruptions that happen. I find myself wishing there was a way to make all those eruptions more visible.

One idea for how to achieve more visibility: add incremental steps to the game log so people can step through each eruption.

Example. Normally, you'd just have turn number 10, followed by turn number 11. But if an eruption happens after turn 10, add incremental save states to the game log at .1 each. So stepping though a game, or hitting the back button during a game, you'd have a sequence of turns like this:

turn 10: tile is highlighted where player played on a volcano 3, turning it into a volcano 4. it would actually show a volcano 4 on the board (unlike the current behavior where volcano 4s never appear, you only see the effects after their explosion).

turn 10.1: game state after first eruption has affected itself and 3 surrounding tiles. let's say this triggers another volcano. the triggered volcano shows the number 4, again, maybe with an eruption symbol.

turn 10.2: game state after the second volcano erupts.

turn 11: no eruptions were caused by this turn, so the next turn goes to a whole number...

Note1: Near the end of a game, during a growth phase, I imagine these incremental steps could be some number larger than ten. I think it would be okay to just keep incrementing them by .1, so after you get to 10.9, go 10.10, then 10.11, etc.

Note2: Now that volcano 4s would appear on the board, maybe even put an eruption symbol at the top of the 4, like from my old mockup:
![image](https://user-images.githubusercontent.com/106923/50390861-03683200-0702-11e9-8b98-7674852bcaa7.png)

**Comment by skotz** [comment]
Is the growth reference necessary with magma chambers no longer being a thing?

**Comment by simondorfman** [comment]
I think the growth reference would still be useful, but I’d update it to the current rules:
1 -> 2 -> 3 -> 4 -> 5=Eruption

**Comment by simondorfman** [comment]
With the current rules, eruption chains don't happen as often. Don't think this is relevant anymore.
