### ISSUE TITLE
What causes Illegal Moves?

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#12]
Looking at some tournament transcripts, I see several games that end in a draw from an illegal move. I've played back the games, but I can't figure out what's causing the illegal move. Any ideas? Spreadsheet attached with some sample games. I believe the games were played with these rules:

```

{
  "MaxMagmaChamberLevel": 4,
  "MaxVolcanoLevel": 8,
  "EruptOverflowEmptyTileAmount": 1,
  "EruptOverflowFriendlyTileAmount": 1,
  "EruptOverflowEnemyTileAmount": -2,
  "EruptOverflowAllowCapture": true,
  "AllowMagmaChamberCaptures": false,
  "AllowVolcanoCaptures": false,
  "TournamentAdjudicateMaxTurns":1000,
  "TournamentAdjudicateMaxSeconds": 1000,
  "CustomSettingsTitle": ""
}

```
[IllegalMove.xlsx](https://github.com/skotz/volcanoes/files/2709603/IllegalMove.xlsx)

**Comment by skotz** [comment]
I think the common denominator in those games is that the Deep Beeline engine returns a null move once all empty or friendly chamber tiles are gone. I'm filtering out volcano moves, so it thinks it doesn't have any moves.

**Comment by skotz** [comment]
Did you truncate the transcript strings in that file to 255 characters?

**Comment by simondorfman** [comment]
@skotz Thanks for the tip about Deep Beeline filtering out volcano moves. Sorry about the truncated strings. Github wouldn't let me upload a CSV. OpenOffice saved to .XLS, but that wasn't accepted. So I installed LibreOffice and converted the .XLS to .XLSX. So I think OpenOffice must have truncated at the save to .XLS step. Attached is a non-truncated version for posterity.
[IllegalMoveNotTruncated.xlsx](https://github.com/skotz/volcanoes/files/2711376/IllegalMoveNotTruncated.xlsx)

**Comment by skotz** [comment]
The issue should be fixed now, so let me know if it happens again.
