### ISSUE TITLE
UI enhancement: reset tournament progress bar text as soon as second tournament starts

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#16]
**Current behavior:**
Given I've run one tournament
When I start a second tournament
Then the tournament progress bar text says "Tournament finished"
(a holdover from the first tournament finishing)
![2018-12-28 00_25_27-window](https://user-images.githubusercontent.com/106923/50505108-66760380-0a37-11e9-903e-209e29fce56f.png)
When the first game of the second tournament finishes, the progress bar text updates to "1/20 tournament games completed"
![2018-12-28 00_29_03-window](https://user-images.githubusercontent.com/106923/50505181-d84e4d00-0a37-11e9-9b65-9bc4419b008e.png)

**Desired behavior:**
Given I've run one tournament
When I start a second tournament
Then the tournament progress bar text says "0/20 tournament games completed"

**Why make this change?:**
Because the user might think the second tournament hasn't actually started when it really has. There can be a long delay before the first game completes and the tournament progress bar text updates to "1/20 tournament games completed"

**Comment by skotz** [comment]
Yeah, the status bar only updates after the first game completes. I can change it to say something immediately after starting a game.
