### ISSUE TITLE
enable running multiple tournaments with different rules

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#17]
Check out the ruleset analysis in the attached zip.

[tournament_analysis.zip](https://github.com/skotz/volcanoes/files/2714433/tournament_analysis.zip)

Go straight to the **tournament_analysis.html** file to see what I've got so far. And you can view the source R markdown code in the **tournament_analysis.Rmd** file.

I'd like to run many more tournaments with the 4 different rulesets. Is there a way to help me automate this somehow? It would be great if I could import the 4 rulesets and tell it how many tournaments to run (e.g. 1000 instead of 10) and then just let it run until all are finished.

**Comment by skotz** [comment]
I suppose you could run several copies of the program, each in it's own folder with it's own rule file. Tournament games are run in parallel using as many threads as it can get from the scheduler, so running too many instances of the game at one time might drastically slow down your computer.

**Comment by skotz** [comment]
And I love data, so thanks for the analysis!

**Comment by simondorfman** [comment]
And I love having an awesome prototype that allows me to try out rules ideas with super-fancy-AI doing a lot of the playtesting legwork. So thanks for the rockstar programming!

**Comment by simondorfman** [comment]
re-ran the tournaments for rules 2-4 because I didn't load the rules changes properly last time. interesting. will dig in more later, but sharing now. will run with many more games. and walk thru some games to see what's going on.

updated analysis:
[tournament_analysis.zip](https://github.com/skotz/volcanoes/files/2715509/tournament_analysis.zip)

**Comment by simondorfman** [comment]
Closing this. I'm running tournaments on different computers. Best to let each computer crunch numbers for just one tournament at a time.
