### ISSUE TITLE
EruptOverflowEnemyTileAmount and EruptOverflowAllowCapture not working as expected

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#18]
(Related to https://github.com/skotz/volcanoes/issues/17)

I was playing back a game:
```
8D 18D G 12D 18A G 2B 13D G 11B 8B G 16D 17D G 5C 7B G 2A 7A G 20C 6C G 1D 1A G 15A 18C G 11D 6A G 15C 14C G 15D 17A G 14B 6B G 10A 5D G 10C 20D G 20B 10B G 13A 16B G 11C 13D G 5D 3D G 8B 20C G 14D 2D G 8C 12B G 19A 16A G 11C 10C G 15D 7B G 2C 1C G 10D 16C G 2A 7A G 15C 6B G 8B 14C G 14B 3A G 11C 10C G 20A 8C G 2B 20C G 1A 11C G 4B 20A G 10D 18C G 9A 11A G 14D 18A G
```
...from a tournament played with these rules:

```
# 3. boost eruption power to destroy opponents, but not oveflow
{
  "MaxMagmaChamberLevel": 4,
  "MaxVolcanoLevel": 8,
  "EruptOverflowEmptyTileAmount": 1,
  "EruptOverflowFriendlyTileAmount": 1,
  "EruptOverflowEnemyTileAmount": -8, #changed from -1 to -8
  "EruptOverflowAllowCapture": false, #changed from true to false
  "AllowMagmaChamberCaptures": false,
  "AllowVolcanoCaptures": false,
  "TournamentAdjudicateMaxTurns": 500,
  "TournamentAdjudicateMaxSeconds": 1800,
  "CustomSettingsTitle": ""
}
```

When I got to turn 28, I was surprised that the eruption wasn't totally destroying the opponent's tile. Screenshot to help illustrate:

![2018-12-28 03_36_29-volcanoes](https://user-images.githubusercontent.com/106923/50511119-f628ab80-0a51-11e9-8924-399cd2bb201d.png)

Am I missing something?

**Comment by skotz** [comment]
It did for me... Did you play that game back with the same rules loaded? Based on the status bar I'd say you're attempting to play that back with the default rules.

![image](https://user-images.githubusercontent.com/11474654/50521627-2db44980-0a8c-11e9-84fd-185db7746650.png)

**Comment by simondorfman** [comment]
To import the edited rules, I was clicking the menu DEBUG -> Reset rules, which was causing the volcano.json to be renamed to volcano.json.DATETIMESTAMP.bak. I was thinking you had added this menu item for that purpose (even though it wasn't labeled "load rules" or something). Silly me. All the analysis games I posted [here](https://github.com/skotz/volcanoes/issues/17) are probably not correct.

Now I'm remembering the proper way is to close the EXE and restart it. It's working for me now. User operator error. You can close this.

**Comment by simondorfman** [comment]
Oh, I guess I can close it.
