### ISSUE TITLE
allow magma chambers to switch sides

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#2]
if you play on an opponent's magma chamber (which previously wasn't allowed), it changes to your color, (and the number increases by one, just like when you play on your own magma chamber).
this would mean your volcanos would be producing magma chambers that your opponent might be able to capitalize on. but if your opponent left them alone, they'd grown into your own volcanos.

example:

1. level 1 blue magma chamber.
2. orange plays on it, makes it a level 2 orange magma chamber, growth happens, making it a level 3 orange magma chamber
3. then blue steals it back, making it a level 4 blue magma chamber, then growth happens, it turns into a level 1 blue volcano. now orange can't steal it back because volcanos can't change color

let's try it and see if it's good or bad. i'm hoping it'll be good, but you never know until you try it...

**Comment by skotz** [comment]
Added two configurable `volcano.json` settings for this: `AllowMagmaChamberCaptures` and `AllowVolcanoCaptures`
