### ISSUE TITLE
Opening books

### ISSUE THREAD

**Issue by skotz** [skotz/volcanoes#24]
Precompute opening books

**Comment by skotz** [comment]
Meh

**Comment by simondorfman** [comment]
@skotz I know you closed this with a "Meh" previously, but maybe this new virtual overlay screenshot will inspire you:
<img width="960" alt="opening analysis looks like A sides are better" src="https://user-images.githubusercontent.com/106923/99177764-50789700-26d2-11eb-8054-a65680b2e060.PNG">

I left this running for a few hours on an empty board and it looks to me like the "A" tiles may be stronger for the opening than the B, C, & D tiles. Not by much. But still, I'm curious to see what the AI would come up with if I left it running for long enough...

**Comment by skotz** [comment]
Cool

**Comment by skotz** [comment]
@simondorfman 

I implemented a basic opening book generated by precomputing the best moves for the first 7 moves of the game. The calculation is done using the normal MCTS engine running for 60 seconds. There are currently 12,643 lines in the book which is enough to cover every possible position 7 moves deep (including growth turns).

The results of a 5 second per move tournament aren't earth shattering, but it did win. I'll create a v0.5.4 download with the book lines.

![image](https://user-images.githubusercontent.com/11474654/100698192-7aca8580-335d-11eb-8530-406d0839c331.png)

It took 3.5 hours to generate the depth-7 book at 60 seconds per position, so you can figure that a 600 seconds-per-position book at the same depth would take about 35 hours.

What I'd like to do in the future is find a way to determine which lines after the depth-7 books are worth precomputing (like only the critical lines) so that we don't have to precompute 160 million positions to go deeper.

**Comment by simondorfman** [comment]
@skotz this is super-interesting! I tried a couple of short tournaments. Running a longer tournament overnight too. I'm surprised that its opening move is N18, which is not an "A" tile.

Playing itself, the first 7 moves are all the same, which makes sense, since it's playing by a book. But it also mostly plays the same against itself for all the moves after number 7 too. Two exceptions out of 10 games:
![image](https://user-images.githubusercontent.com/106923/100710596-92ae0380-3375-11eb-8ec5-a025286385c6.png)

**Comment by simondorfman** [comment]
Is there any way I could compute the opening book with longer think times? I’m really curious to see what it comes up with.

**Comment by skotz** [comment]
Yeah. Right now it's hard coded to 60 seconds and doesn't give any progress indication, but I can change that. I'm very interested in generating a stronger book.

I'm also messing around with a hashing strategy that might speed up search speeds.

**Comment by skotz** [comment]
Coming soon (in the CTRL+D DEBUG menu).

![image](https://user-images.githubusercontent.com/11474654/100820336-985a2680-3413-11eb-9dd9-a61c544af774.png)

**Comment by skotz** [comment]
Added this to v0.5.5. Please send any books generated over 60 seconds my way please.

You may need to run this outside of the Programs folder (like copy the files to a folder on the desktop instead of running it from the installed location) since it directly modifies a file in that location. 

Also, I added several MCTS variations that use hashing, opening books, and fast win searching. The "trio" version uses all three. Initial tests seem like they could be quite strong. Let me know the results from any longer tournaments you happen to run.

**Comment by simondorfman** [comment]
Sweet!

I kicked off a 600 seconds book generation. Will post it here when it finishes.

**Comment by simondorfman** [comment]
Needed the computer for something else so had to cancel it. Will restart it again later.

Did a simulation on other computer and the new AIs are looking very strong:
<img width="327" alt="2020-12-02 18_11_39-tourney-table-20201202010011 csv - Excel" src="https://user-images.githubusercontent.com/106923/100946874-edf10a80-34c9-11eb-9eb7-31d251c05031.png">
<img width="219" alt="2020-12-02 00_59_11-Volcanoes - Tournament" src="https://user-images.githubusercontent.com/106923/100946882-f21d2800-34c9-11eb-9d82-431d1776a4a6.png">

**Comment by skotz** [comment]
Unfortunately I think there's a bug with my hashing again... If you open
the list of games for that tournament you'll see a lot of time
adjudications. My theory is that it's running out of memory.

**Comment by simondorfman** [comment]
Yeah, I see what you mean, 43 of 250 are AdjudicateTime. I'll see if I can verify memory is the issue. Maybe I can monitor memory while it's running somehow...

**Comment by skotz** [comment]
And unfortunately I'm treating timeouts as draws instead of declaring the last player to move (whoever didn't time out) the winner, so it's not a great representation of the results. I think I might have a fix. Need to test.

**Comment by skotz** [comment]
Fixed timeouts so that it's a win for the last player to move instead of a draw. Fixed tournament timeout calculations so that it doesn't let some engines think for way longer than they should while others only get to think for a fraction of their time before being declared a loser.

**Comment by simondorfman** [comment]
[openings.dat.zip](https://github.com/skotz/volcanoes/files/5647986/openings.dat.zip)
@skotz here's the opening book I generated with 600 seconds.
