### ISSUE TITLE
Replace Volcano/MagmaChamber labels with Coordinate labels

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#25]
I've been trying rules where there are no magma chambers, only volcanoes. So the volcano label isn't useful with these rules. And I've been wishing that all 80 spaces on the board would show their coordinate label (e.g. 1A through 20D). So I was thinking maybe these two things could be accomplished by adding two more value pairs to the volcano.json, something like this:

```
  "ShowVolcanoMagmaLabels": false,
  "ShowCoordinateLabels": true,
```

**Comment by skotz** [comment]
Added coordinate label toggle to the UI. There's already a `ShowTileNames` setting in `graphics.json` so I didn't add a new one.
