### ISSUE TITLE
UI feature: add Turn Clock

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#27]
**What:**
Add a "Turn Clock" to the lower left. The red arrow rotates clockwise and points to the current player's turn.

Bonus: outline each donut-segment with yellow (to make it extra clear whose turn it is now, red arrow points to it, and it's outlined with a yellow highlight).

**Why:**
Makes it easier to see 1) whose turn it is, and 2) what will happen next, and 3) the overall flow of the turns.

**Mockup:**

Turn Clock could probably fit in lower-left. SVG mockup also attached (created in Inkscape so you can edit easily in Inkscape if you want).
[TurnClock.svg.zip](https://github.com/skotz/volcanoes/files/4057558/TurnClock.svg.zip)

![TurnClockMockupLowerLeft](https://user-images.githubusercontent.com/106923/72317836-22649980-3660-11ea-8f38-842a0fb03320.png)

**Comment by skotz** [comment]
Note to self: `Graphics.FillPie`

**Comment by skotz** [comment]
Done (without words since to me it seemed intuitive enough). Can always be enhanced later.
