### ISSUE TITLE
Add Five Keyboard Shortcuts

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#29]
Keyboard shortcut ideas:

1. Control-N = New Game
2. Left Arrow = Previous Move
3. Right Arrow = Next Move
4. Home = First Move
5. End = Last Move

It would be nice to make the shortcuts discoverable too, by putting them in the dropdown menu or mouse-over-tooltips.

Screenshot with red arrows pointing from keyboard key to GUI element:
<img width="1204" alt="VolcanoesKeyboardShortcutIdeas" src="https://user-images.githubusercontent.com/106923/72409308-f3ffc080-372a-11ea-9c6c-9fc39ca404b0.png">

**Comment by skotz** [comment]
Added
