### ISSUE TITLE
Enable AI to play itself in tournaments

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#30]
I'm trying to answer questions like:
Is there a first-player advantage?
Is there a second-player advantage?

To try and answer those questions, I'd like to have the same AI play itself many times. After many simulations, I hope the first player and second player will each win 50% of the time.

**Comment by skotz** [comment]
There's a self play option under the engine menu that lets you play an engine against itself for as many games as you'd like.

**Comment by skotz** [comment]
Added for tournaments as well. https://github.com/skotz/volcanoes/releases/tag/v0.3.3
