### ISSUE TITLE
Scale fonts when resizing game window

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#32]
When I maximize the game, the fonts get smaller and harder to read. Would be cool if the fonts would keep the same ratio in size to the triangles. Screenshot:

<img width="1429" alt="MaximizedWindowComparedToStartingSize" src="https://user-images.githubusercontent.com/106923/72704856-7b7c7380-3b1f-11ea-9247-ad4974cf186a.png">

**Comment by skotz** [comment]
Done
