### ISSUE TITLE
update turn playback UI to start count at zero instead of one

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#34]
Example:
![image](https://user-images.githubusercontent.com/106923/72706399-8df8ac00-3b23-11ea-8b22-545c6ad765cf.png)

UI on top right shows **1/58**. No pieces have been played on the board yet. So I think it should show **0/58**.

![image](https://user-images.githubusercontent.com/106923/72706569-f8115100-3b23-11ea-9bf8-8aa7663c07d2.png)
Now UI on top right shows **2/58**. Only one piece has been played on the board. So I think it should show **1/58**.

When browsing through games, these changes will make it less confusing, I think.

**Comment by skotz** [comment]
So when you're playing a game you want to know what move is pending (i.e., you're waiting for the first turn of the game) but when you're playing back a saved game you want to know what move was just played (i.e., the first move is the first turn).

**Comment by simondorfman** [comment]
I'm not sure. I think having it different for playback of saved games, versus playback of game you're currently playing, would be confusing. I guess I was thinking the 2/58 numbers on the upper right could start at zero. And the "Turn 2" on the upper left in orange could start at 1. But maybe that's also confusing? I will think about it more. But I'm open to your ideas since I'm still confused about what experience would be not confusing.

**Comment by simondorfman** [comment]
@skotz I think you set the turn count to start with zero with the 0.4.1 release, so I'll close this one.
