### ISSUE TITLE
save Tournament results in some writable folder

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#35]
Given Volcanoes was installed using [the latest installer](https://github.com/skotz/volcanoes/releases/download/v0.4.0/Setup-Volcanoes-v0.4.0.exe)
When a tournament is run
Then the tournament results fail to save to _C:\Program Files (x86)\Volcanoes_, probably because of permissions

Solution ideas: Ask user where to save the results when the tournament ends? Or just save them to the desktop or someplace reasonable?

**Comment by skotz** [comment]
Decided to default to the My Games folder under My Documents like most games do on Windows.
