### ISSUE TITLE
Update README.md rules

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#37]
I couldn't figure out how to create a branch and pull request (permissions? because it's your repo...?) so instead I'll create this ticket and ask you to update the README.md [README.txt](https://github.com/skotz/volcanoes/files/4101647/README.txt) with the attached (README.txt, couldn't upload .md file type). Also, please upload the attached image to the \volcanoes\Concept\History folder?

<img width="790" alt="z-history-20200122" src="https://user-images.githubusercontent.com/106923/72962368-c265a580-3d79-11ea-910b-46b6f576f9d0.png">

**Comment by skotz** [comment]
The updated readme says an eruption makes `enemy volcanoes regress one level on the growth track` but it actually just destroys them completely.

**Comment by skotz** [comment]
Done
