### ISSUE TITLE
add equator line to help with planet recognition and direction orientation

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#39]
Following the style of many globes, put a red line where the equator is like this:
![equator_1b](https://user-images.githubusercontent.com/106923/73272935-cdb93680-41a8-11ea-97df-7d403f4733e5.png)

...and when the world is rotated, rotate the equator with it like this:
![equator_2b](https://user-images.githubusercontent.com/106923/73272958-d578db00-41a8-11ea-9063-5d992b90d854.png)

**Comment by skotz** [comment]
Found an interesting solution to make this work, however due to the alignment of the tiles being slightly off, the lines don't look completely straight.

![image](https://user-images.githubusercontent.com/11474654/73596724-64a82a80-44ea-11ea-90c8-5742e35c9a6b.png)

**Comment by simondorfman** [comment]
Looks good enough to me! I think it's helpful. We'll see what other people think.

**Comment by simondorfman** [comment]
Part of release 0.4.3 so closing this.
