### ISSUE TITLE
Add option for Volcano to go dormant

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#40]
I'd like to try these rules:
* after a volcano erupts, instead of resetting to a level 1 volcano, it stays a level 5 volcano
    - it is no longer affected by growth, nor friendly neighbor eruptions. It stays frozen as a dormant, level-5 volcano. It can still be destroyed by an enemy neighbor eruption. Otherwise, it just sits there.
    - It can still be part of a volcano ridge to win the game.
* volcano.json might look like this: `"EruptionsBeforeDormancy": 1,`
    - Then I could try values higher than 1 also, allowing a volcano to erupt a few times before going dormant.

Sidenote: maybe bringing back the spawning of baby volcanoes could work with the above rule.
`"EruptOverflowEmptyTileAmount": 1,`

Why do I want to try this feature? I was playing a game against a friend and we got into an endless loop of turns. :( Too complicated for the Ko rule. Here's the game transcript up until the loop happened:
`6C 7A G 12C 6B G 11A 11B G 7C 6A G 11D 7C+ G 7B 11A G 11A+ 12D G 11C 11D+ G 11A+ 11C+ G 11B 11A G 11A+ 11B+ G 11B 11A G 11A+ 11B+ G`

**Comment by skotz** [comment]
Implemented this locally, but initial tests indicate a forced win for player 2.

![image](https://user-images.githubusercontent.com/11474654/73503069-b9d02900-4390-11ea-8491-dd98f0abcb42.png)

[tourney-20200130063945.zip](https://github.com/skotz/volcanoes/files/4137009/tourney-20200130063945.zip)

**Comment by skotz** [comment]
Actually it looks like that was a bug. Either way, I need to run more tests before I release a new version. Attached is a test version with the new `AllowDormantVolcanoes` set to true and `EruptOverflowEmptyTileAmount` set to 1.

[Volcanoes-Dormant-Test.zip](https://github.com/skotz/volcanoes/files/4137100/Volcanoes-Dormant-Test.zip)

**Comment by simondorfman** [comment]
Awesome. Thanks for implementing this so fast.

I really like the idea of dormant volcanoes, but not sure if I actually like them in practice yet. I tried a few games with `EruptOverflowEmptyTileAmount` set to 1 but didn't really like it. If things can grow that fast, I feel like killing them should be easier, so I tried `MaxVolcanoLevel` set to 3. It's kind of interesting, but also changes so fast. Not sure about this. Didn't like it at first, but it's growing on me. Will contemplate and run some tournaments.

Next, I tried `EruptOverflowEmptyTileAmount` set to 0 with `MaxVolcanoLevel` set back at 5. Kind of liking it so far...

I know you intend to run more tests, but in case it helps, I noticed this:
once a dormant volcano is on a space,
after it's destroyed by an eruption,
playing a new volcano on that space shows up as the darker color (but it should be the lighter color).
Um, now I can't reproduce that. I swear it happened. I am very tired though...

**Comment by simondorfman** [comment]
I'm thinking these rules might kind of negate the need for "plus" moves (increasing the growth of a volcano that already exists, instead of starting a new volcano). Or at least make them much less common. Not sure how I feel about that. Would simplify it, you only have one type of action on your turn. Simplifying is generally good. But the plus moves do add allow for extra tactical fights, which sometimes are good. Sometimes they're a distraction. But the possibility of plus moves adds some nice tension I think. Makes you think things like: Should I grow my line around this fight? Or spend plus moves to engage in some tactical stuff?

**Comment by skotz** [comment]
Done. Off by default. Enable with `"AllowDormantVolcanoes": true`
