### ISSUE TITLE
dormant volcano messes up color of new volanoes in same spot

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#44]
Steps to reproduce:
1. download zip version of release 0.4.3
2. unzip to folder
3. copy attached json file into that folder [volcano.json.zip](https://github.com/skotz/volcanoes/files/4143685/volcano.json.zip) (unzip first)
4. open attached game transcript [ColorOfVolcanoBug.vgt.zip](https://github.com/skotz/volcanoes/files/4143686/ColorOfVolcanoBug.vgt.zip)

You'll see the issue on tiles N26 & N27. Screenshot:

![image](https://user-images.githubusercontent.com/106923/73605248-8db7d200-4561-11ea-8522-0eb8a398daeb.png)

**Comment by skotz** [comment]
Fixed
