### ISSUE TITLE
Rules change idea: regress opponent's pieces two levels instead of one

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#6]
Change this effect from eruption:

> Spaces with your opponent's pieces regress **one level** on the growth track (**level 1** magma chambers become empty spaces).

...to this:

> Spaces with your opponent's pieces regress **two levels** on the growth track (**level 1 and level 2** magma chambers become empty spaces).

Why?
It's very easy to block a path by playing a level 1 magma chamber. It very rarely happens that a level 1 chamber is wiped out by a volcano. This increases the chance of that happening. Maybe even this will not have much effect. Then maybe it would be worth trying a further increase to three levels like this:

> Spaces with your opponent's pieces regress **three levels** on the growth track (**level 1, level 2 and level 3** magma chambers become empty spaces).

**Comment by skotz** [comment]
Created two `volcano.json` settings for this: `EruptOverflowEnemyTileAmount` is the levels deducted from an enemy tile during an eruption, and `EruptOverflowAllowCapture` will determine whether excessive levels turn into empty tiles or whether they can wrap around into the opponents pieces. For instance, if you subtract 3 from 1 you can either clear the tile or get -2 which turns into a tile of the opponents color of value 2. Basically it's either a capture or a clear.
