### ISSUE TITLE
back and forward buttons

### ISSUE THREAD

**Issue by simondorfman** [skotz/volcanoes#8]
add a back button and a forward button. would allow a game in progress or a saved game to be studied. include the growth phase as a turn that can be stepped through. emulate browser back/forward buttons (gray out the buttons when they can't be pressed). maybe include a turn-counter-clock-face-thingy next to the turn number so it's easier to see where in the turn sequence you are.

this might be too many ideas for one "issue". maybe this should just be: add a back and forward button for a game currently being played.

subsequent ideas could be:
enable saving a game and restarting from a saved game
enable stepping through a saved game from tournament results file

**Comment by skotz** [comment]
Added navigation controls.

![image](https://user-images.githubusercontent.com/11474654/50378641-c8c8a180-05fc-11e9-88e1-55aac1689029.png)

Added a way to save and load games.

![image](https://user-images.githubusercontent.com/11474654/50378650-ed247e00-05fc-11e9-9b56-d0bb44f1bd42.png)
